### ISSUE TITLE
owned.sol - temporary critical vulnerability after creation

### ISSUE THREAD

**Issue by gundas** [CORIONplatform/solidity#161]
A number of contracts (_tokenDB, providerDB, schellingLight_ and _exchangeLight_) extend  the `owned` contract.

Once such contract is created on the blockchain, the `owner` of the contract is not set - anyone can call `replaceOwner()` function and take-over the contract. 
Or, for example, anyone could create unlimited number of Tokens by calling `increase(..)` function on the 'tokenDB' while the owner is not set yet. 

I would suggest copying the implementation from [OpenZeppelin](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/ownership/Ownable.sol#L17-L19), where the owner is always first set to the creator of the contract:

```
  function owned() {
    owner = msg.sender;
  }
```

**Comment by iFA88** [comment]
Hey, yes I know this. This is not a vulnerability!
If I deploy first time a database contract, I need create with an empty owner because I need pair the two contract. For pairing I need to know every address, but on the first deploy I don't know the second contract address.

The process is:
 - Deploying the `Database` contract ( with empty provider).
 - Deploying the `Main` contract with the `Database` contract address as constructor parameter.

At the end I have an paired contract prepared for replace.

So it should be.

If you check `schellingLight` and `exchangeLight` contract constructor functions, the owner are set :)

**Comment by gundas** [comment]
I still think it is a big security risk - there is an opportunity to mint an unlimited amount of tokens while the owner is not set. 

There is no reason to have this risk:
- you create a `Database` contract, the `owner` is set to your account (`msg.sender`)
- you create the `Main` contract
- you call the `replaceOwner(..)` on the `Database` contract  to set the owner to the `Main`

**Comment by iFA88** [comment]
Yeah, this mean after I deploy the database contract the `attacker` should fast call the contract, before I deploy the second (Main) contract.
1. I think this will never happen.
2. If this happens, I drop the contracts and don't use them.
