### ISSUE TITLE
approve + transferFrom mechanism vulnerability.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#6]
I've recently described that `approve` + `transferFrom` is a couple of two different transactions. This mechanism can cause problems and is potentially insecure.
Re-approval attack is described [here](https://drive.google.com/file/d/0ByMtMw2hul0EN3NCaVFHSFdxRzA/view).
I recommend that you remove the `approve`s and `transferFrom`s from the token contract, because there is no need to implement such mechanisms, because the implementation of the fallback function execution on transfer is enough for transaction hadling realisation.

Current `transactionCount` variable implementation can't solve re-approval issue.

**Comment by iFA88** [comment]
Can you please explain with an example solidity code?

**Comment by Dexaran** [comment]
The variable `transactionCount` can be artificially specified at any external call.
It is a dummy variable that is always equal to 0 now (I'm assuming that you want to increase it each time that `approve` happens, like a transaction nonce).

The attack:
Alice is approving X tokes, then wants to reapprove Y tokens.
Bob is queuing these transactions:
Alice.transferFrom(address, X, 0);
Alice.transferFrom(address, Y, 0);
Alice.transferFrom(address, X, 1);
Alice.transferFrom(address, Y, 1);
Alice.transferFrom(address, X, 2);
Alice.transferFrom(address, Y, 2);
 ........
And so on.

As the result of this a couple of transactions with `transactionsCount` for X and `transactionsCoun + 1` for Y tokens would submit.

**Comment by iFA88** [comment]
If I understand well the attack systematic:
Alice approving X tokens to Bob.
Alice approving again Y tokens to Bob, BUT Before the approving Bob transfers the tokens and after the new approving transfers again the tokens. That's mean Bob has transferred X+Y tokens, rigtht?

If you use my code, then:
Alice approving X tokens for 0 transactions count to Bob.
Alice approving again Y tokens for 0 transactions count to Bob, BUT Bob transfers the X tokens (the transaction count increasing), and then the contract will throw the 'approving Y tokens' transaction for ALice because the transaction count is different.

**Comment by Dexaran** [comment]
Confirmed. This will work.

I think this solution is not user friendly and inconvenient. I strongly recommend that you exclude from the contract of the token `approve`,` approveAndCall`, `receiveApproval`,` allowance` functions, `_allowance` structure and `allowance_` mapping.
The approval mechanism is rudimentary, and it is not required for anything, while it can create an excellent field for creating errors and mistakes.
The contract that should "do something with tokens" should do it after receiving of these tokens. Function `receiveCorionToken` should be always used instead of working with approvals.

Excluding of this functions will simplify the code and exclude a lot of possibilities of hidden mistakes. (Such are re-approval attacks / approve that was accepted into uncle block instead of mainchain etc. )

**Comment by iFA88** [comment]
Thanks for the tip but we need that in the wallet. This is a business element.

**Comment by Dexaran** [comment]
If you need it for any reasons I think that we can use a [more user-friendly variant](https://drive.google.com/file/d/0ByMtMw2hul0EN3NCaVFHSFdxRzA/view): 
Use `uint _currentApproved` instead of `_transactionsCoun`.
This assumes that Alice should approve X tokens
`approve(Bob, X, 0)`
then approve Y tokens
`approve(Bob, Y, X)` and if the _currentApproved amount is not equal to X the approve would be thrown.

This approach assumes that Alice doesn't need to know how many transactions Bob has performed. Also Alice doesn't need to check contract variables.
Alice should only know how much did she approved Bob to withdraw and if the amount is less the re-approve will not happen.

**Comment by iFA88** [comment]
You mean, the third parameter should the original approved amount, or the left amount?

**Comment by Dexaran** [comment]
Original approved amount.

Example:
Alice should approve Bob to receive 199 Corions. Alice now wants to approve Bob to receive 150 Corions.
Alice is calling `approve(Bob, 150, 199)` (An analogue if the remaining approved amount is less than 199, and Bob has already withdrawn something, not re-approving him again).

**Comment by iFA88** [comment]
Okay, if we think in wallet backend for both method I need check the SQL for 1. transactionCount and 2. originalApprovedAmount

**Comment by iFA88** [comment]
I have thought about that. I think the best method is the transaction count (like nonce, maybe i rename it to).

Your method is bad as fair I understand:
You can not approve the same amount for the spender.
# or
The attack is still available, because you need give the original approve for the re-aprove. The Bob can transfer found before the reaprove and then transfer again.

If I have wrong understood please write a sample solidity code. Thank you!
