### ISSUE TITLE
No check for overflow.

### ISSUE THREAD

**Issue by Dexaran** [CORIONplatform/solidity#71]
There is no check for overflow: https://github.com/CORIONplatform/solidity/blob/master/schelling.sol#L154

Why not to use `SafeMath` here also?

**Comment by pyskell** [comment]
Adding to this, there are many other cases where SafeAdd and SafeSub are not used:
Using `-` instead of `safeSub`:
![image](https://user-images.githubusercontent.com/9665963/28331560-90f9d838-6bbf-11e7-8ad1-c14faff34a6e.png)

Using `+` instead of `safeAdd`:
![image](https://user-images.githubusercontent.com/9665963/28331603-af9d5418-6bbf-11e7-93a4-e106ce1a10b9.png)

**Comment by iFA88** [comment]
@pyskell can you please give a line detailed list from that? Thank you!

**Comment by pyskell** [comment]
I can't do that easily from my machine at the moment, this is basically a quick search of every place that contains the following operators: `-` `--` `-=` `+` `++` `+=` All of which should be able to be replaced with `safeSub` and `safeAdd`.
